[tools]
jq = "latest"
yq = "latest"
bat = "latest"
ripgrep = "latest"
fzf = "latest"
chezmoi = "latest"
k9s = "latest"
starship = "latest"
talosctl = "latest"
go = "latest"
kubectl = "latest"
zoxide = "latest"
kubie = "latest"
usage = "latest"
"github:Schniz/fnm" = "latest"
crane = "latest"
kubelogin = "latest"
kubeswitch = "latest"
