[tools]
jq = "latest"
yq = "latest"
bat = "latest"
ripgrep = "latest"
fzf = "latest"
chezmoi = "latest"
k9s = "latest"
starship = "latest"
talosctl = "latest"
go = "latest"
kubectl = "latest"
zoxide = "latest"
usage = "latest"
"github:Schniz/fnm" = "latest"
crane = "latest"
kubelogin = "latest"
kubeswitch = "latest"
lima = "latest"
"github:cachix/secretspec" = "latest"
"github:stackitcloud/stackit-cli" = "latest"
opentofu = "latest"
git-cliff = "latest"
argocd = "latest"
just = "latest"
"github:ankitpokhrel/jira-cli" = "latest"
"github:kubara-io/kubara" = "latest"
"github:mykso/myks" = "latest"
direnv = "latest"
helm = "latest"

[settings]
lockfile = true
